### ISSUE TITLE
Open and Closed Issue and Pull request 

### ISSUE THREAD

**Issue by Mezekr** [Mezekr/Github-Repository-Analysis#1]
Wie können wir die offenen und geschlossenen Issue- und Pull-Requests eines Repositorys erhalten?

**Comment by aayusranjan** [comment]
check it out here https://youtu.be/IHaTbJPdB-s
and if u want any help feel free to connect

**Comment by Mezekr** [comment]
Thanks very much for your Help. We are working with GitHub REST API to analyze a Repository.

**Comment by Mezekr** [comment]
Das Problem wurde gelöst.
